# Requrienment 1: Create a persistent User Identification and History System for a Quiz Application. (Get rid of all global variables)
# Use Cookies to track users and store their quiz history in a database and welcome them back.
# If they are new users, create a new profile for them.
from flask import Flask, render_template, request, redirect, url_for, session, make_response
import json
import random

app = Flask(__name__)
# Create a secret key for session management
app.secret_key = 'secretkey'

# Display a welcome page to the user with a Start Quiz link
# Start session to track user progress
# Generated by Copilot using: "Fix my home function to use cookies and sessions instead of global variables"
@app.route('/')
def home():
    username = request.cookies.get('username')
    if username:
        history = session.get('history', [])
        return render_template('index.html', returning=True, username=username, history=history)
    else:
        return render_template('new_user.html')

@app.route('/setname', methods=['POST'])
def setname():
    username = request.form.get('username')
    if not username:
        return redirect(url_for('home'))

    user_response = make_response(redirect(url_for('home')))
    user_response.set_cookie('username', username)
    session['history'] = []
    return user_response

# Display quiz questions and handle user answers
@app.route('/quiz', methods=['GET', 'POST'])
def quiz():

    # Generated by Copilot using: "Fix my quiz function to use session variables instead of global variables"
    if 'question_num' not in session:
        session['question_num'] = 0
        session['score'] = 0

    # Esentially the same process with global variables, but using session variables instead
    if request.method == 'POST':
        the_answer = request.form.get('answer')
        question_num = session['question_num']
        score = session['score']

        correct_answer = QUESTIONS[questions[question_num - 1][0]][0]
        if the_answer == correct_answer:
            score += 1
            the_result = "Correct!"
        else:
            the_result = "Incorrect!"

        # Save updated score
        session['score'] = score

        return render_template('question_result.html',
                               question_result=the_result,
                               question=questions[question_num - 1][0],
                               answer=the_answer)

    # Increment question number for GET request
    session['question_num'] += 1
    question_num = session['question_num']

    if question_num >= len(questions):
        return redirect(url_for('result'))

    next_question = questions[question_num - 1][0]
    options = random.sample(questions[question_num - 1][1], len(questions[question_num - 1][1]))

    return render_template('quiz.html',
                           num=question_num,
                           question=next_question,
                           options=options)


# Display the quiz results to the user
@app.route('/result')
def result():
    score = session.get('score', 0)
    question_num = session.get('question_num', 0)

    history = session.get('history', [])
    history.append({'score': score, 'total': len(questions)})
    session['history'] = history

    template = render_template('result.html', score=score, total=len(questions))
    # Reset for next quiz
    session['score'] = 0
    session['question_num'] = 0
    return template

# Prepare quiz questions
def prepare_questions(all_questions, num_questions):
    num_questions = min(num_questions, len(all_questions))
    return random.sample(list(all_questions.items()), num_questions)

# Main Quiz Steps: prepare questions, run the quiz, give feedback.
# Read in the quiz questions from a JSON file
NUM_QUESTIONS_PER_QUIZ = 5
question_file = open('questions.json')
QUESTIONS = json.load(question_file)
print(f'Loaded {len(QUESTIONS)} questions.')
questions = prepare_questions(QUESTIONS, NUM_QUESTIONS_PER_QUIZ)

# Run the application
if __name__ == '__main__':
    app.run(debug=True)
    