# Requirement 1: Create a persistent User Identification and History System for a Quiz Application. (Get rid of all global variables)
# Use Cookies to track users and store their quiz history in a database and welcome them back.
# If they are new users, create a new profile for them.

# Requirement 2: Add a hint system where users can request a hint on a question. For balance, deduct points when hints are used, or limit hints to one per quiz.
from flask import Flask, render_template, request, redirect, url_for, session, make_response
import json
import random

app = Flask(__name__)
# Create a secret key for session management
app.secret_key = 'secretkey'

# Display a welcome page to the user with a Start Quiz link
# Start session to track user progress
# Generated by Copilot using: "Fix my home function to use cookies and sessions instead of global variables"
@app.route('/')
def home():
    username = request.cookies.get('username')
    if username:
        history = session.get('history', [])
        return render_template('index.html', returning=True, username=username, history=history)
    else:
        return render_template('new_user.html')

@app.route('/setname', methods=['POST'])
def setname():
    username = request.form.get('username')
    if not username:
        return redirect(url_for('home'))

    user_response = make_response(redirect(url_for('home')))
    user_response.set_cookie('username', username)
    session['history'] = []
    return user_response

# Display quiz questions and handle user answers
# Generated by Copilot using: "Add a hint system where users can request a hint on a question." Esentially adding a hint function to the quiz function that reduces as it is used and provoeds no penalty if not used and only one hint per quiz.
@app.route('/quiz', methods=['GET', 'POST'])
def quiz():
    if 'question_num' not in session:
        session['question_num'] = 0
        session['score'] = 0
        session['hint_used'] = False

    question_num = session['question_num']

    if request.method == 'POST':
        if 'hint' in request.form:
            question_text, qdata = questions[question_num - 1]
            hint_text = qdata.get('hint', 'No hint available.')

            if not session.get('hint_used', False):
                session['score'] = max(0, session['score'] - 1)
                session['hint_used'] = True

            return render_template('quiz.html',
                                   num=question_num,
                                   question=question_text,
                                   options=random.sample(qdata['choices'], len(qdata['choices'])),
                                   hint=hint_text,
                                   hint_used=True)

        the_answer = request.form.get('answer')
        question_text, qdata = questions[question_num - 1]
        correct_answer = qdata['answer']

        if the_answer == correct_answer:
            session['score'] += 1
            result = "Correct!"
        else:
            result = "Incorrect!"

        return render_template('question_result.html',
                               question_result=result,
                               question=question_text,
                               answer=the_answer)

    session['question_num'] += 1
    question_num = session['question_num']

    if question_num > len(questions):
        return redirect(url_for('result'))

    question_text, qdata = questions[question_num - 1]
    options = random.sample(qdata['choices'], len(qdata['choices']))

    return render_template('quiz.html',
                           num=question_num,
                           question=question_text,
                           options=options,
                           hint_used=session.get('hint_used', False))


# Display the quiz results to the user
@app.route('/result')
def result():
    score = session.get('score', 0)
    question_num = session.get('question_num', 0)

    history = session.get('history', [])
    history.append({'score': score, 'total': len(questions)})
    session['history'] = history

    template = render_template('result.html', score=score, total=len(questions))
    # Reset for next quiz
    session['score'] = 0
    session['question_num'] = 0
    session['hint_used'] = False
    return template

# Prepare quiz questions
def prepare_questions(all_questions, num_questions):
    items = list(all_questions.items())
    selected = random.sample(items, min(num_questions, len(items)))
    return selected

# Main Quiz Steps: prepare questions, run the quiz, give feedback.
# Read in the quiz questions from a JSON file
NUM_QUESTIONS_PER_QUIZ = 5
question_file = open('new_questions.json')
QUESTIONS = json.load(question_file)
print(f'Loaded {len(QUESTIONS)} questions.')
questions = prepare_questions(QUESTIONS, NUM_QUESTIONS_PER_QUIZ)

# Run the application
if __name__ == '__main__':
    app.run(debug=True)
    